name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Menetapkan direktori kerja default untuk semua 'run' steps di job ini
    defaults:
      run:
        working-directory: ./appalarm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        # Perintah ini sekarang akan berjalan di dalam folder 'appalarm'
        run: chmod +x gradlew

      - name: Build with Gradle
        # Perintah ini juga akan berjalan di dalam folder 'appalarm'
        run: ./gradlew build
