name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          # Path sekarang sudah benar, langsung menunjuk ke file di root
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        # Tidak perlu working-directory karena semua file ada di root
        run: npm install

      - name: Run tests
        run: npm test
