name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup lingkungan Node.js
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm' # Opsi ini mempercepat instalasi di masa depan

      # 3. Install dependencies
      # Tidak perlu working-directory karena package.json ada di root
      - name: Install dependencies
        run: npm install

      # 4. Menjalankan skrip tes (jika ada)
      # Tidak perlu working-directory
      - name: Run tests
        run: npm test
