name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Menetapkan direktori kerja default untuk semua 'run' steps di job ini
    defaults:
      run:
        working-directory: ./MyalarmApp

    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup lingkungan Node.js
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # Beri tahu cache di mana harus mencari package-lock.json
          cache: 'npm'
          cache-dependency-path: MyalarmApp/package-lock.json

      # 3. Install dependencies
      # 'working-directory' tidak perlu ditulis lagi karena sudah diatur di 'defaults'
      - name: Install dependencies
        run: npm install

      # 4. Menjalankan skrip tes (jika ada)
      - name: Run tests
        run: npm test
